#!/usr/bin/python2.7
# -*-coding:utf-8 -*

fichier = raw_input('Nom du fichier? ')
with open(fichier, 'r') as f:
    liste = f.readlines()
# afficher nbre de mots 
   
sens = raw_input('1. Ang-->Fr ; 2.Fr-->Ang? ')
    
revoir = []
for mot in liste:
    mot = mot.split(',')
    print ''
    if sens == '1':
        rep = raw_input(mot[0] + ' ')
        if rep != '' and rep in mot[1]:
        #  ?sens du point d'exclam
            print 'ok'
       # else:
        if rep = .. sortie   
        else:
            revoir.append(mot)
            print 'non: ', 
    else:
        rep = raw_input(mot[1] + ' ')
        if rep != '' and rep in mot[0]:
            print 'ok'
        else:
            revoir.append(mot)
            print 'non: ', 
    print mot[0], ':', mot[1]
            
sortie = '\n\n'
for mot in revoir:
    sortie += mot[0] + ',' + mot[1]
with open('a-revoir.txt', 'a') as f:
    f.write(sortie)
        
